# Generated by Django 6.1 on 2026-09-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athletevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='injury_type',
            field=models.CharField(blank=True, choices=[('acl_tear', 'ACL Tear'), ('mcl_injury', 'MCL Injury'), ('meniscus_injury', 'Meniscus Injury'), ('hamstring_strain', 'Hamstring Strain'), ('quadriceps_strain', 'Quadriceps Strain'), ('ankle_sprain', 'Ankle Sprain'), ('achilles_injury', 'Achilles Tendon Injury'), ('shoulder_injury', 'Shoulder Injury'), ('lower_back_injury', 'Lower Back Injury'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='recovery_status',
            field=models.CharField(blank=True, choices=[('fully_recovered', 'Fully Recovered'), ('partially_recovered', 'Partially Recovered'), ('currently_injured', 'Currently Injured')], max_length=30),
        ),
    ]
