# Generated by Django 6.1 on 2026-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athleteprofile_injury_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletevideo',
            name='risk_factors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletevideo',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='athletevideo',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
