"""add_binary_storage_cols_to_videos

Revision ID: 507b90721148
Revises: 20ddf52c0e83
Create Date: 2026-08-19 23:38:14.390176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507b90721148'
down_revision: Union[str, Sequence[str], None] = '20ddf52c0e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('videos', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('videos', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'file_size')
    op.drop_column('videos', 'content_type')
    op.drop_column('videos', 'original_filename')
    op.drop_column('videos', 'file_data')
    # ### end Alembic commands ###
