"""initial_schema_mentor_aligned_uuid

Revision ID: 5d34925c67e8
Revises: 
Create Date: 2026-08-15 11:05:26.028193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d34925c67e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('ATHLETE', 'COACH', 'PHYSIOTHERAPIST', 'SPORTS_SCIENTIST', 'ADMINISTRATOR', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_code', sa.String(length=50), nullable=False),
    sa.Column('sport_type', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('dominant_side', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_profiles_athlete_code'), 'athlete_profiles', ['athlete_code'], unique=True)
    op.create_index(op.f('ix_athlete_profiles_id'), 'athlete_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_athlete_profiles_user_id'), 'athlete_profiles', ['user_id'], unique=True)
    op.create_table('injury_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('injury_type', sa.String(length=100), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('expected_recovery_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('mechanism_of_injury', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_records_athlete_id'), 'injury_records', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_injury_records_date_occurred'), 'injury_records', ['date_occurred'], unique=False)
    op.create_index(op.f('ix_injury_records_id'), 'injury_records', ['id'], unique=False)
    op.create_index(op.f('ix_injury_records_recorded_by_id'), 'injury_records', ['recorded_by_id'], unique=False)
    op.create_table('physical_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('assessor_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('assessment_type', sa.String(length=100), nullable=False),
    sa.Column('mobility_score', sa.Float(), nullable=True),
    sa.Column('strength_score', sa.Float(), nullable=True),
    sa.Column('balance_symmetry', sa.Float(), nullable=True),
    sa.Column('movement_notes', sa.Text(), nullable=True),
    sa.Column('assessment_data', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_assessments_assessment_date'), 'physical_assessments', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_physical_assessments_assessor_id'), 'physical_assessments', ['assessor_id'], unique=False)
    op.create_index(op.f('ix_physical_assessments_athlete_id'), 'physical_assessments', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_physical_assessments_id'), 'physical_assessments', ['id'], unique=False)
    op.create_table('training_loads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('rpe_score', sa.Integer(), nullable=False),
    sa.Column('calculated_load', sa.Float(), nullable=False),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=True),
    sa.Column('heart_rate_max', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='chk_duration_positive'),
    sa.CheckConstraint('rpe_score >= 1 AND rpe_score <= 10', name='chk_rpe_score_range'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_loads_athlete_id'), 'training_loads', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_loads_id'), 'training_loads', ['id'], unique=False)
    op.create_index(op.f('ix_training_loads_session_date'), 'training_loads', ['session_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_loads_session_date'), table_name='training_loads')
    op.drop_index(op.f('ix_training_loads_id'), table_name='training_loads')
    op.drop_index(op.f('ix_training_loads_athlete_id'), table_name='training_loads')
    op.drop_table('training_loads')
    op.drop_index(op.f('ix_physical_assessments_id'), table_name='physical_assessments')
    op.drop_index(op.f('ix_physical_assessments_athlete_id'), table_name='physical_assessments')
    op.drop_index(op.f('ix_physical_assessments_assessor_id'), table_name='physical_assessments')
    op.drop_index(op.f('ix_physical_assessments_assessment_date'), table_name='physical_assessments')
    op.drop_table('physical_assessments')
    op.drop_index(op.f('ix_injury_records_recorded_by_id'), table_name='injury_records')
    op.drop_index(op.f('ix_injury_records_id'), table_name='injury_records')
    op.drop_index(op.f('ix_injury_records_date_occurred'), table_name='injury_records')
    op.drop_index(op.f('ix_injury_records_athlete_id'), table_name='injury_records')
    op.drop_table('injury_records')
    op.drop_index(op.f('ix_athlete_profiles_user_id'), table_name='athlete_profiles')
    op.drop_index(op.f('ix_athlete_profiles_id'), table_name='athlete_profiles')
    op.drop_index(op.f('ix_athlete_profiles_athlete_code'), table_name='athlete_profiles')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
