from typing import Annotated
from uuid import UUID

# pyrefly: ignore [missing-import]
from fastapi import APIRouter, Depends, HTTPException, status
# pyrefly: ignore [missing-import]
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.athlete import Athlete
from app.models.user import RoleEnum, User
from app.schemas.athlete import (
    AthleteCreate,
    AthleteSelfCreate,
    AthleteResponse,
    AthleteUpdate,
)
from app.core.dependencies import get_current_user, require_roles


router = APIRouter(
    prefix="/athletes",
    tags=["Athletes"],
)


# Roles that can manage athlete profiles.
ATHLETE_MANAGEMENT_ROLES = (
    RoleEnum.ADMINISTRATOR,
    RoleEnum.COACH,
    RoleEnum.PHYSIOTHERAPIST,
)


# Roles that can view athlete profiles.
ATHLETE_VIEW_ROLES = (
    RoleEnum.ADMINISTRATOR,
    RoleEnum.COACH,
    RoleEnum.PHYSIOTHERAPIST,
    RoleEnum.SPORTS_SCIENTIST,
)


# ============================================================
# CREATE ATHLETE PROFILE
# ============================================================

@router.post(
    "",
    response_model=AthleteResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create an athlete profile",
)
def create_athlete(
    athlete_in: AthleteCreate,
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> Athlete:

    # Athletes can only create their own profile.
    if current_user.role == RoleEnum.ATHLETE:

        if athlete_in.user_id != current_user.user_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Athletes can only create their own profile.",
            )

    # Other users need an authorized management role.
    elif current_user.role not in ATHLETE_MANAGEMENT_ROLES:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have permission to create athlete profiles.",
        )

    # Verify target user exists.
    target_user = (
        db.query(User)
        .filter(User.user_id == athlete_in.user_id)
        .first()
    )

    if target_user is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User account not found.",
        )

    # Only Athlete accounts can have an athlete profile.
    if target_user.role != RoleEnum.ATHLETE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Athlete profile can only be linked to an Athlete user.",
        )

    # Check whether a profile already exists.
    existing_profile = (
        db.query(Athlete)
        .filter(Athlete.user_id == athlete_in.user_id)
        .first()
    )

    if existing_profile:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An athlete profile already exists for this user.",
        )

    athlete = Athlete(
        **athlete_in.model_dump(),
    )

    db.add(athlete)

    try:
        db.commit()
        db.refresh(athlete)

    except Exception:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while creating the athlete profile.",
        )

    return athlete


# ============================================================
# CREATE CURRENT ATHLETE'S OWN PROFILE
# ============================================================

@router.post(
    "/me",
    response_model=AthleteResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create current athlete's profile",
)
def create_my_athlete_profile(
    athlete_in: AthleteSelfCreate,
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> Athlete:

    # Only Athlete accounts can use this endpoint.
    if current_user.role != RoleEnum.ATHLETE:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only Athlete users can create an athlete profile.",
        )

    # Check whether this athlete already has a profile.
    existing_profile = (
        db.query(Athlete)
        .filter(Athlete.user_id == current_user.user_id)
        .first()
    )

    if existing_profile:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An athlete profile already exists for this user.",
        )

    # user_id comes from the authenticated JWT.
    # athlete_id is automatically generated by the model.
    athlete = Athlete(
        user_id=current_user.user_id,
        **athlete_in.model_dump(),
    )

    db.add(athlete)

    try:
        db.commit()
        db.refresh(athlete)

    except Exception:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while creating the athlete profile.",
        )

    return athlete


# ============================================================
# UPSERT CURRENT ATHLETE PROFILE (Create or Update)
# ============================================================

@router.put(
    "/me",
    response_model=AthleteResponse,
    status_code=status.HTTP_200_OK,
    summary="Create or update current athlete's profile",
)
def upsert_my_athlete_profile(
    athlete_in: AthleteSelfCreate,
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> Athlete:
    """
    Upsert the authenticated athlete's profile.

    - If no profile exists, create one (HTTP 200).
    - If a profile already exists, apply a partial update (HTTP 200).
    - ``user_id`` is always sourced from the JWT — the client cannot supply it.
    """

    # Only Athlete accounts may use this endpoint.
    if current_user.role != RoleEnum.ATHLETE:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only Athlete users can manage their own profile.",
        )

    athlete = (
        db.query(Athlete)
        .filter(Athlete.user_id == current_user.user_id)
        .first()
    )

    if athlete is None:
        # Profile does not exist — create it.
        athlete = Athlete(
            user_id=current_user.user_id,
            **athlete_in.model_dump(exclude_none=True),
        )
        db.add(athlete)
    else:
        # Profile exists — apply supplied fields.
        update_data = athlete_in.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(athlete, field, value)

    try:
        db.commit()
        db.refresh(athlete)

    except Exception:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while saving the athlete profile.",
        )

    return athlete


# ============================================================
# LIST ATHLETE PROFILES
# ============================================================

@router.get(
    "",
    response_model=list[AthleteResponse],
    summary="List athlete profiles",
)
def list_athletes(
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> list[Athlete]:

    # Athlete can only see their own profile.
    if current_user.role == RoleEnum.ATHLETE:

        profile = (
            db.query(Athlete)
            .filter(Athlete.user_id == current_user.user_id)
            .first()
        )

        return [profile] if profile else []

    # Other authorized roles can view all athletes.
    if current_user.role not in ATHLETE_VIEW_ROLES:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have permission to view athlete profiles.",
        )

    return (
        db.query(Athlete)
        .order_by(Athlete.athlete_id)
        .all()
    )


# ============================================================
# GET CURRENT ATHLETE PROFILE
# ============================================================

@router.get(
    "/me",
    response_model=AthleteResponse,
    summary="Get current athlete profile",
)
def get_my_athlete_profile(
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> Athlete:

    if current_user.role != RoleEnum.ATHLETE:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only Athlete users can access this endpoint.",
        )

    athlete = (
        db.query(Athlete)
        .filter(Athlete.user_id == current_user.user_id)
        .first()
    )

    if athlete is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Athlete profile not found.",
        )

    return athlete


# ============================================================
# UPDATE CURRENT ATHLETE PROFILE
# ============================================================

@router.patch(
    "/me",
    response_model=AthleteResponse,
    summary="Update current athlete's profile",
)
def update_my_athlete_profile(
    athlete_in: AthleteUpdate,
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> Athlete:

    if current_user.role != RoleEnum.ATHLETE:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only Athlete users can update their own profile.",
        )

    athlete = (
        db.query(Athlete)
        .filter(Athlete.user_id == current_user.user_id)
        .first()
    )

    if athlete is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Athlete profile not found.",
        )

    update_data = athlete_in.model_dump(
        exclude_unset=True
    )

    for field, value in update_data.items():
        setattr(athlete, field, value)

    try:
        db.commit()
        db.refresh(athlete)

    except Exception:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while updating the athlete profile.",
        )

    return athlete


# ============================================================
# GET ATHLETE BY ID
# ============================================================

@router.get(
    "/{athlete_id}",
    response_model=AthleteResponse,
    summary="Get an athlete profile",
)
def get_athlete(
    athlete_id: UUID,
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> Athlete:

    athlete = (
        db.query(Athlete)
        .filter(Athlete.athlete_id == athlete_id)
        .first()
    )

    if athlete is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Athlete profile not found.",
        )

    # Athlete can only access their own profile.
    if current_user.role == RoleEnum.ATHLETE:

        if athlete.user_id != current_user.user_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="You can only access your own athlete profile.",
            )

    elif current_user.role not in ATHLETE_VIEW_ROLES:

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have permission to view athlete profiles.",
        )

    return athlete


# ============================================================
# UPDATE ATHLETE BY ID
# ============================================================

@router.patch(
    "/{athlete_id}",
    response_model=AthleteResponse,
    summary="Update an athlete profile",
)
def update_athlete(
    athlete_id: UUID,
    athlete_in: AthleteUpdate,
    current_user: Annotated[
        User,
        Depends(get_current_user),
    ],
    db: Session = Depends(get_db),
) -> Athlete:

    athlete = (
        db.query(Athlete)
        .filter(Athlete.athlete_id == athlete_id)
        .first()
    )

    if athlete is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Athlete profile not found.",
        )

    # Athlete can update only their own profile.
    if current_user.role == RoleEnum.ATHLETE:

        if athlete.user_id != current_user.user_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="You can only update your own athlete profile.",
            )

    elif current_user.role not in ATHLETE_MANAGEMENT_ROLES:

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have permission to update athlete profiles.",
        )

    update_data = athlete_in.model_dump(
        exclude_unset=True
    )

    for field, value in update_data.items():
        setattr(athlete, field, value)

    try:
        db.commit()
        db.refresh(athlete)

    except Exception:
        db.rollback()

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while updating the athlete profile.",
        )

    return athlete


# ============================================================
# DELETE ATHLETE PROFILE
# ============================================================

@router.delete(
    "/{athlete_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete an athlete profile",
)
def delete_athlete(
    athlete_id: UUID,
    current_user: Annotated[
        User,
        Depends(require_roles(RoleEnum.ADMINISTRATOR)),
    ],
    db: Session = Depends(get_db),
) -> None:

    athlete = (
        db.query(Athlete)
        .filter(Athlete.athlete_id == athlete_id)
        .first()
    )

    if athlete is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Athlete profile not found.",
        )

    db.delete(athlete)
    db.commit()